apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

bases:
  - ../../base

namePrefix: staging-

commonLabels:
  environment: staging

configMapGenerator:
  - name: nodejs-app-config
    behavior: merge
    literals:
      - NODE_ENV=staging
      - LOG_LEVEL=info
      - ENABLE_METRICS=true
      - ENABLE_DETAILED_ERRORS=true

patches:
  - path: patches.yaml

patchesStrategicMerge:
  - service-patch.yaml

images:
  - name: ghcr.io/GITHUB_USERNAME/nodejs-cicd-pipeline
    newName: ghcr.io/satish-cards/nodejs-cicd-pipeline
    newTag: c84ce778c3dd1d8bdd46ce3386efd405335f6c72
